server:
  port: 13000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:

        #项目root
        - id: draw-root
          uri: lb://draw
          predicates:
            - Path=/api/draw/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /$\{segment}
        #以admin为路径的都转到后台
        - id: admin-route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /renren-fast/$\{segment}

  application:
    name: mall-gateway
